### ISSUE TITLE
Handle connection loss

### ISSUE THREAD

**Issue by rsoeldner** [tfausak/wuss#11]
Hello,

I couldn't find a way to handle a connection loss, does something exist already ?

Cheers

**Comment by tfausak** [comment]
Wuss is a pretty thin layer around [the `websockets` package](https://hackage.haskell.org/package/websockets-0.12.4.0). Anything that deals with reconnecting should be the same between the two packages. Unfortunately I don't have any examples on hand. Are you trying to reconnect as a client or a server?

**Comment by rsoeldner** [comment]
yes, or at least  I need a notification that the connection is broken,. I will check _websockets_ package. Thank you :+1:

**Comment by tfausak** [comment]
I don't know off the top of my head what happens when the connection is broken, but I'd assume an exception is thrown. So you'll probably end up using something like [`Control.Exception.catch`](https://www.stackage.org/haddock/lts-11.1/base-4.10.1.0/Control-Exception.html#v:catch) along with some custom handler code.

**Comment by rsoeldner** [comment]
@tfausak TY, worked for me :+1:

**Comment by tfausak** [comment]
Great! If it's convenient, can you paste the code that worked for you? That way if someone else shows up with the same question I can point them here 😄
