### ISSUE TITLE
Expose `settingDisableCertificateValidation `

### ISSUE THREAD

**Issue by joshmyzie2** [tfausak/wuss#2]
It would be nice if the user could disable certificate verification.

**Comment by tfausak** [comment]
How do you imagine this looking? `settingDisableCertificateValidation` is part of `TLSSettings`, which is part of `ConnectionParams`.

**Comment by joshmyzie2** [comment]
Yeah, I couldn't think of anything that clean.  I'd probably change `tlsSettings` to `defaultTlsSettings`, export it, and add a `TLSSettings` parameter to `runSecureClientWith`.

**Comment by tfausak** [comment]
That's more or less what I had in mind too. I think there are a couple problems with it though:

1. I want [`runSecureClient`](https://hackage.haskell.org/package/wuss-1.0.0/docs/Wuss.html#v:runSecureClient) to be a drop-in replacement for [`runClient`](https://hackage.haskell.org/package/websockets-0.9.5.0/docs/Network-WebSockets.html#v:runClient). Likewise for [`runSecureClientWith`](http://hackage.haskell.org/package/wuss-1.0.0/docs/Wuss.html#v:runSecureClientWith) and [`runClientWith`](http://hackage.haskell.org/package/websockets-0.9.5.0/docs/Network-WebSockets.html#v:runClientWith).

2. The `TLSSettings` are really part of the `ConnectionParams`, so it makes more sense to me to pass in the params instead of the settings. But I don't know that you'd ever want to change any of the other params.

**Comment by tfausak** [comment]
I created a pull request (#3) to fix this issue. It is a little more complicated than I would like. I think you may be better off doing the setup yourself and calling [`runClientWithStream`](https://hackage.haskell.org/package/websockets-0.9.5.0/docs/Network-WebSockets.html#v:runClientWithStream) directly.

**Comment by joshmyzie2** [comment]
Yeah, it might not be worth adding for the sake of simplicity.  I'll defer to you on that judgement.

**Comment by tfausak** [comment]
I don't think I'll merge #3. I will however add a note to the documentation about using `runClientWithStream` to disable certificate validation.
